module.exports = {
    origin: '#flights-search-origin-1',
    destination: '#flights-search-destination-1',
    passengersDropdown: '#flights-search-open-pax-btn',
    adults: '[data-action="add"][data-pax-type="adult"]',
    removeAdults: '[data-action="remove"][data-pax-type="adult"]',
    fromDatepicker: '.js-fs-departure-date [data-device="desktop"]',
    toDatepicker: '.js-fs-return-date [data-device="desktop"]',
    calendarSelected: '.pika-lendar .is-selected',
    calendarEndRage: '.pika-lendar .is-selected.is-endrange',
    calendarButton: 'button',
    searchFlightsBtn: '#flights-search-cta',
    searchFareLoader: '.fareLoaderDiv',
    flightSearchSummary: '#flights-results-summary',
    flightSummary: {
      from: '#flights-results-summary .flight-search-summ__item:first-child > p:nth-child(1) span',
      to: '#flights-results-summary .flight-search-summ__item:first-child > p:nth-child(3) span',
      fromDate: '#flights-results-summary .flight-search-summary__container .row:nth-child(2) .flight-search-summ__item:nth-child(2) p:first-child span',
      toDate: '#flights-results-summary .flight-search-summary__container .row:nth-child(2) .flight-search-summ__item:nth-child(2) p:last-child span',
      travellerCount: '#flights-results-summary .flight-search-summary__container .row:nth-child(2) .flight-search-summ__item:nth-child(4) p span'
    },
    ekIATACode: '.filters__checkbos-fix .filter-options:first-child .form-group .font-base:contains(\"EK: Emirates\")',
    xyIATACode: '.filters__checkbos-fix .filter-options:last-child .form-group .font-base:contains(\"XY: flynas\")',
    firstDepartingFlightAirline: '#flights-filters-airline-leg-0-check-exclude-0',
    firstReturnFlightAirline: '#flights-filters-airline-leg-1-check-exclude-0',
    resetReturnFlightAirlineChoice: '#flights-filters-can-show-airline-cta-1',
    firstFlightSelectButton: '#flights-results-select-cta-btn-desktop-0',
    firstFlightPrice: '#serch-result-item-group-0 .search-result-action-a .search-result-item__itinerary-price-detail .price-display:nth-child(2)',
    continueToPaymentButton: '#flights-summary-go-to-payment-cta'
};